/*
* Login Action Types
*/

const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN'
const UPDATE_TICKETS = 'UPDATE_TICKETS'
const SHOW_TICKETS = 'SHOW_TICKETS'

/* Export All constants*/
export {
  UPDATE_CURRENT_USER,
  UPDATE_AUTH_TOKEN,
  UPDATE_TICKETS,
  SHOW_TICKETS
}