/*
* Login Action Types
*/

const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN'
const UPDATE_TICKETS = 'UPDATE_TICKETS'
const UPDATE_FILTER = 'UPDATE_FILTER'
const SHOW_TICKET = 'SHOW_TICKET'
const UPDATE_MODAL = 'UPDATE_MODAL'
const UPDATE_FLASH = 'UPDATE_FLASH'

/* Export All constants*/
export {
  UPDATE_CURRENT_USER,
  UPDATE_AUTH_TOKEN,
  UPDATE_TICKETS,
  SHOW_TICKET,
  UPDATE_FILTER,
  UPDATE_MODAL,
  UPDATE_FLASH
}