/*
* Login Action Types 
*/
const REQUEST_BEFORE_START = 'REQUEST_BEFORE_START'
const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
const REQUEST_FAILURE = 'REQUEST_FAILURE'
const REQUEST = 'REQUEST'


/* Export All constants*/
export {
  REQUEST_BEFORE_START,
  REQUEST_SUCCESS,
  REQUEST_FAILURE,
  REQUEST
}